version: '2.4'

services:
  django:
    build: .
    command: bash.sh
    depends_on:
      # - elasticsearch
      - postgres
      - redis
    environment:
      DOTENV: ${DOTENV:-develop}
      FLOWER_PORT: 5555
      PGHOST: postgres
      PGUSER: postgres
      REDIS_ADDRESS: redis:6379
    image: interaction/project_template:local
    volumes:
      - .:/opt/project_template
      - /var/run/docker.sock:/var/run/docker.sock

  # elasticsearch:
  #   environment:
  #     ES_JAVA_OPTS: ${ES_JAVA_OPTS:--Xms500m -Xmx500m}
  #   image: interaction/elasticsearch-icu:7-alpine
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data

  postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata  # Store data in subdirectory of volume mount point, per PostgreSQL recommendations
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:12.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data

volumes:
  # elasticsearch-data:
  postgres-data:
  redis-data:
