version: "2.3"
services:
  base:
    env_file: .env.local
    environment:
      TERM: # Get from environment
    image: interaction/project_template:local
    volumes:
      - ./:/opt/project_template
  bash:
    command: setup-django.sh bash.sh
    extends: base
    links:
      - postgres
      - redis
    ports:
      - 8000:8000
  celery:
    command: setup-django.sh celery.sh
    extends: base
    links:
      # - elasticsearch
      - postgres
      - redis
  celerybeat:
    command: setup-django.sh celerybeat.sh
    extends: base
    links:
      - postgres
      - redis
  celeryflower:
    command: setup-django.sh supervisor.sh
    environment:
      SUPERVISORD_PROGRAM: celeryflower
      VIRTUAL_HOST_WEIGHT: 1
      VIRTUAL_HOST: flower.*
    extends: base
    links:
      - postgres
      - redis
    ports:
      - 8000
  django:
    build: .
    command: setup-django.sh supervisor.sh
    environment:
      VIRTUAL_HOST: '*'
    extends: base
    links:
      # - celery
      # - celerybeat
      # - celeryflower
      # - elasticsearch
      - postgres
      - redis
    ports:
      - 8000
  # elasticsearch:
  #   image: interaction/elasticsearch-icu:1-alpine
  #   ports:
  #     - 9200
  haproxy:
    image: 'dockercloud/haproxy:1.6.3'
    links:
      - celeryflower
      - django
    ports:
      # - 80:80
      # - 443:443
      - 1936:1936
      - 8000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:9.4-alpine
    ports:
      - 5432
  redis:
    command: redis-server --appendonly yes
    image: redis:3-alpine
    ports:
      - 6379
