version: '3.6'

x-project: &project
  env_file: .env.local
  image: interaction/project_template:local
  volumes:
    - .:/opt/project_template

services:
  celery:
    << : *project
    command: setup-wait.sh celery.sh --concurrency 1

  celerybeat:
    << : *project
    command: setup-wait.sh celerybeat.sh

  celeryflower:
    << : *project
    command: setup-wait.sh celeryflower.sh
    environment:
      VIRTUAL_HOST: 'flower.*'
      VIRTUAL_HOST_WEIGHT: 1
    ports:
      - 8080

  # elasticsearch:
  #   environment:
  #     ES_JAVA_OPTS: ${ES_JAVA_OPTS:-'-Xms500m -Xmx500m'}
  #   image: interaction/elasticsearch-icu:5-alpine

  haproxy:
    image: dockercloud/haproxy
    links:
      - celeryflower
      - runserver
    ports:
      - ${HAPROXY_PORT:-80}:80
      - 1936
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:9.5-alpine
    ports:
      - 5432

  redis:
    image: redis:3-alpine
    ports:
      - 6379

  runserver:
    << : *project
    command: setup-wait.sh runserver.sh
    environment:
      VIRTUAL_HOST: '*'
    ports:
      - 8000

  shell:
    << : *project
    build: .
    command: bash.sh
    depends_on:
      - celery
      - celerybeat
      - celeryflower
      # - elasticsearch
      - haproxy
      - postgres
      - redis
      - runserver
